jira fetcher -> allow several fetch sessions per invocation
athenianco/metadata pull request #236
Opened 2020-08-26 13:02 UTC by lwsanty

+ add node selector to jira fetch trigger and consistency checker

close [[DEV-607]]
close [[DEV-752]]

Signed-off-by: lwsanty <lwsanty@gmail.com>

2020-08-26 13:35 UTC, dennwc requested changes

2020-08-26 13:35 UTC, dennwc commented on jira_fetcher.go
> +	// pageSize represents the amount of issues to be fetched during a CF invocation
I think this comment should be on the `totalSize`.

2020-08-26 13:35 UTC, dennwc commented on jira_fetcher.go
> +		if len(issues) == 0 {
This condition is wrong. You must exit the loop here instead of killing the function.

2020-08-26 13:35 UTC, dennwc commented on terraform/modules/fetcher/consistency.tf
> +            node_selector = {
Can you please PR/commit this change separately. Not sure why it's here and why only for those pods.

2020-08-26 14:01 UTC, lwsanty commented on terraform/modules/fetcher/consistency.tf
> +            node_selector = {
https://github.com/athenianco/metadata/pull/237

2020-08-26 14:01 UTC, lwsanty commented on jira_fetcher.go
> +		if len(issues) == 0 {
discussed

Done.

2020-08-26 14:02 UTC, lwsanty commented on jira_fetcher.go
> +	// pageSize represents the amount of issues to be fetched during a CF invocation
Done.

2020-08-26 15:10 UTC, dennwc commented on jira_fetcher.go
> +				return nil
This is the "gap" I was talking about. We need to `break` here as well.

2020-08-26 15:59 UTC, lwsanty commented on jira_fetcher.go
> +				return nil
Done.

2020-08-27 08:51 UTC, dennwc approved these changes

2020-08-27 08:52 UTC, merged