jira -> fetch projects and components
athenianco/metadata pull request #246
Opened 2020-09-02 14:17 UTC by lwsanty

close [[DEV-805]]

Signed-off-by: lwsanty <lwsanty@gmail.com>

2020-09-02 15:15 UTC, dennwc requested changes

2020-09-02 15:15 UTC, dennwc commented on cmd/jira/main.go
> +	psProjects, err := pubsub.NewPublisherFromEnv("JIRA_FETCH_PROJECTS_TOPIC")
This is why I asked you to introduce `Type` in the Jira events ;) You can now set `Type = "project"` and use the same topic instead of having more CFs and topics.

2020-09-02 15:26 UTC, lwsanty commented on cmd/jira/main.go
> +	psProjects, err := pubsub.NewPublisherFromEnv("JIRA_FETCH_PROJECTS_TOPIC")
Done.

2020-09-02 15:32 UTC, dennwc commented on jira_projects_fetcher.go
> +type JiraProjectsFetcher struct {
And the same for the CF: you can use the same CF, but `switch` on the event type.

2020-09-02 15:41 UTC, dennwc requested changes

2020-09-02 15:41 UTC, dennwc commented on sql/migrations/011_jira_project_and_components.down.sql
> +ALTER TABLE jira.issue DROP COLUMN project_id;
Wrap the whole file into tx:
```sql
BEGIN;
...
COMMIT;
```

2020-09-02 15:41 UTC, dennwc commented on sql/migrations/011_jira_project_and_components.up.sql
> +COMMIT;
It's safer to wrap it all into one tx.

2020-09-02 15:41 UTC, dennwc commented on jira/types/types.go
> +	ComponentIDs []string
```suggestion
	ComponentIDs []ComponentID
```

2020-09-02 15:41 UTC, dennwc commented on jira/database/database_pg.go
> +	ErrEmptyProjectID   = errors.New("a valid project ID must be specified")
Too many `ErrEmptyXxxID`. Let's keep the `ErrEmptyAccID`, but make all others a single and generic `ErrEmptyObjectID` and `ErrEmptyObjectKey`.

2020-09-02 15:41 UTC, dennwc commented on jira_projects_fetcher.go
> +			if err := f.db.CreateComponent(ctx, c); err != nil {
It will override the same component over and over again. Is there `Component.GetListWithContext` or something along the lines? Or at least add a map `seenComponents map[ComponentID]struct{}` to not add ones that were inserted already.

2020-09-03 09:41 UTC, lwsanty commented on jira_projects_fetcher.go
> +type JiraProjectsFetcher struct {
Done.

2020-09-03 09:41 UTC, lwsanty commented on sql/migrations/011_jira_project_and_components.down.sql
> +ALTER TABLE jira.issue DROP COLUMN project_id;
Done.

2020-09-03 09:41 UTC, lwsanty commented on sql/migrations/011_jira_project_and_components.up.sql
> +COMMIT;
Done.

2020-09-03 09:41 UTC, lwsanty commented on jira/types/types.go
> +	ComponentIDs []string
Done.

2020-09-03 09:41 UTC, lwsanty commented on jira/database/database_pg.go
> +	ErrEmptyProjectID   = errors.New("a valid project ID must be specified")
Done.

2020-09-03 09:42 UTC, lwsanty commented on jira_projects_fetcher.go
> +			if err := f.db.CreateComponent(ctx, c); err != nil {
discussed it https://athenian.slack.com/archives/DQRGXTTT4/p1599063629032400

2020-09-03 12:46 UTC, dennwc requested changes

2020-09-03 12:46 UTC, dennwc commented on terraform/gen.go
> +  jira_mapping_topic 	  = google_pubsub_topic.jira_mapping_topic.name
Can you please revert this file?

2020-09-03 12:46 UTC, dennwc commented on sql/migrations/012_jira_project_and_components.up.sql
> +    PRIMARY KEY(acc_id, project_id, id)
We need to check if the component ID is unique or not. This is important.

2020-09-03 12:46 UTC, dennwc commented on jira_fetcher.go
> +	credsData, err := f.prov.GetPrivateKeyData(ctx, int64(ev.AccID))
Setting up the credentials is the same as in `handleIssues`. Please move it into a function instead of copy-pasting it.

2020-09-03 12:46 UTC, dennwc commented on jira_fetcher.go
> +	var components []*types.Component
```suggestion
	var components []types.Component
```

2020-09-03 16:02 UTC, lwsanty commented on jira_fetcher.go
> +	credsData, err := f.prov.GetPrivateKeyData(ctx, int64(ev.AccID))
Done.

2020-09-03 16:02 UTC, lwsanty commented on sql/migrations/012_jira_project_and_components.up.sql
> +    PRIMARY KEY(acc_id, project_id, id)
Done.

2020-09-03 16:02 UTC, lwsanty commented on terraform/gen.go
> +  jira_mapping_topic 	  = google_pubsub_topic.jira_mapping_topic.name
Done.

2020-09-03 16:20 UTC, dennwc approved these changes

2020-09-03 16:54 UTC, merged