jira handshake initial steps
athenianco/metadata pull request #249
Opened 2020-09-04 16:21 UTC by lwsanty

Signed-off-by: lwsanty <lwsanty@gmail.com>

2020-09-15 17:17 UTC, dennwc requested changes

2020-09-15 17:17 UTC, dennwc commented on jira/client/transport/jwt.go
> +func (v qshVar) string() string {
```suggestion
func (v qshVar) String() string {
```

2020-09-15 17:17 UTC, dennwc commented on jira/client/transport/jwt.go
> +	return fmt.Sprintf("%x", sum), nil
`hex.EncodeToString`

2020-09-15 17:17 UTC, dennwc commented on jira/client/transport/jwt.go
> +	if _, err := io.Copy(hash, strings.NewReader(s)); err != nil {
```
hash.Write([]byte(s))
```

2020-09-15 17:17 UTC, dennwc commented on jira/client/transport/unified.go
> +	req2 := cloneRequest(req)
It should be safe to pass the original `req` here. No need to clone.

2020-09-15 17:17 UTC, dennwc commented on jira/client/transport/unified.go
> +	return nil, fmt.Errorf("failed to route the request")
`"no auth credentials set"` would be a better explanation; also, `errors.New`.

2020-09-15 17:17 UTC, dennwc commented on jira/database/database.go
>  	GetAccIDs(ctx context.Context) ([]types.AccID, error)
Is it still used?

2020-09-15 17:17 UTC, dennwc commented on jira/database/database_pg.go
> +	if err := db.QueryRowContext(ctx, `INSERT INTO
It's really hard to read. Can you indent it the same way as other queries (for example in the GH package)?

2020-09-15 17:17 UTC, dennwc commented on sql/migrations/015_jira_installation.up.sql
> +    acc_id BIGSERIAL NOT NULL,
This must be a `PRIMARY KEY`.

2020-09-15 17:17 UTC, dennwc commented on sql/migrations/015_jira_installation.up.sql
> +    base_url text NOT NULL,
Instead of making this a PK, define it as `UNIQUE`.

2020-09-15 17:17 UTC, dennwc commented on pkeyprocessor/pkeyprocessor.go
> +// TODO: move to https://github.com/athenianco/cloud-common
Please do.

2020-09-15 17:17 UTC, dennwc commented on jira/database/database.go
> +	GetInstallationByURL(ctx context.Context, url string) (*Installation, error)
Seems unused.

2020-09-16 11:26 UTC, lwsanty commented on athenian/database_pg.go
> +	row := db.db.QueryRow(ctx, `SELECT id, created_at, secret, secret_salt FROM public.accounts WHERE id = $1`, int64(id))
Done.

2020-09-16 11:26 UTC, lwsanty commented on jira/types/types.go
> +	AccID          AccID
Done.

2020-09-16 11:26 UTC, lwsanty commented on jira_webhook.go
> +	helloWorld = `<!DOCTYPE html>
Done.

2020-09-16 11:26 UTC, lwsanty commented on jira_webhook.go
> +  "baseUrl": "%[2]s",
could you please elaborate?

2020-09-16 11:26 UTC, lwsanty commented on jira/client/transport/jwt.go
> +func (v qshVar) string() string {
Done.

2020-09-16 11:26 UTC, lwsanty commented on jira/database/database_pg.go
> +	if err := db.QueryRowContext(ctx, `INSERT INTO
Done.

2020-09-16 11:26 UTC, lwsanty commented on sql/migrations/015_jira_installation.up.sql
> +    acc_id BIGSERIAL NOT NULL,
Done.

2020-09-16 11:27 UTC, lwsanty commented on sql/migrations/015_jira_installation.up.sql
> +    base_url text NOT NULL,
Done.

2020-09-16 11:27 UTC, lwsanty commented on pkeyprocessor/pkeyprocessor.go
> +// TODO: move to https://github.com/athenianco/cloud-common
Done.

2020-09-16 11:27 UTC, lwsanty commented on jira/database/database.go
> +	GetInstallationByURL(ctx context.Context, url string) (*Installation, error)
Done.

2020-09-16 12:20 UTC, lwsanty commented on jira_webhook.go
> +  "baseUrl": "%[2]s",
Done.

2020-09-16 14:37 UTC, lwsanty commented on jira/database/database.go
>  	GetAccIDs(ctx context.Context) ([]types.AccID, error)
Done.

2020-09-16 14:37 UTC, lwsanty commented on jira/client/transport/unified.go
> +	return nil, fmt.Errorf("failed to route the request")
Done.

2020-09-16 14:37 UTC, lwsanty commented on jira/client/transport/jwt.go
> +	if _, err := io.Copy(hash, strings.NewReader(s)); err != nil {
Done.

2020-09-16 14:37 UTC, lwsanty commented on jira/client/transport/unified.go
> +	req2 := cloneRequest(req)
Done.

2020-09-16 14:37 UTC, lwsanty commented on jira/client/transport/jwt.go
> +	return fmt.Sprintf("%x", sum), nil
Done.

2020-09-24 15:10 UTC, dennwc commented
Some conflicts here. Will soon review it again.

2020-09-28 11:35 UTC, dennwc reviewed
@lwsanty LGTM! Now the important question: have you tested it in action? :)

2020-09-28 18:49 UTC, lwsanty commented
@dennwc several points to mention:
- yes I was testing it when submitted the PR
- I was not testing it after all the review fixes done
- we cannot roll it now on staging or elsewhere because it requires installations db's data to be 'fixed'

2020-10-13 17:04 UTC, dennwc approved these changes

2020-10-14 12:15 UTC, merged