jira issue labels lowercase
athenianco/metadata pull request #251
Opened 2020-09-11 11:09 UTC by lwsanty

close [[DEV-842]]

Signed-off-by: lwsanty <lwsanty@gmail.com>

2020-09-11 15:02 UTC, dennwc requested changes

2020-09-11 15:02 UTC, dennwc commented on sql/migrations/015_jira_issue_labels_lowercase.up.sql
> +UPDATE jira.issue set labels = lower(labels::text)::text[];
Something sketchy is going on here. Why labels (an array) are cast to plain string and then back? I think it doesn't work and probably concatenates all the labels into one.

2020-09-14 10:23 UTC, lwsanty commented on sql/migrations/015_jira_issue_labels_lowercase.up.sql
> +UPDATE jira.issue set labels = lower(labels::text)::text[];
It works though
```sql
testdb_1=# select labels from jira.issue ;
            labels            
------------------------------
 
 {"Performance, Enhancement"}
 {"A, b"}
 {"bA, Ba"}
 {"performance, enhancement"}
(5 rows)

testdb_1=# UPDATE jira.issue set labels = lower(labels::text)::text[];
UPDATE 5
testdb_1=# select labels from jira.issue ;
            labels            
------------------------------
 
 {"performance, enhancement"}
 {"a, b"}
 {"ba, ba"}
 {"performance, enhancement"}
(5 rows)

testdb_1=# 
```
If you see any dangerous cases with this please let me know, but taking into account that jira labels are also validated I don't see problems so far.

2020-09-14 15:11 UTC, dennwc commented on sql/migrations/015_jira_issue_labels_lowercase.up.sql
> +UPDATE jira.issue set labels = lower(labels::text)::text[];
```
{"Performance, Enhancement"}
```
Notice how the quotes are placed? you have a single element `"Performance, Enhancement"` instead of two elements. This must be fixed.

2020-09-15 10:41 UTC, lwsanty commented on sql/migrations/015_jira_issue_labels_lowercase.up.sql
> +UPDATE jira.issue set labels = lower(labels::text)::text[];
Done.

2020-09-15 13:31 UTC, dennwc commented on sql/migrations/016_jira_issue_labels_lowercase.up.sql
> +CREATE OR REPLACE FUNCTION lower(text[]) RETURNS text[] LANGUAGE SQL IMMUTABLE AS
Can you please wrap it into `BEGIN; ... COMMIT;`? LGTM otherwise.

2020-09-15 14:32 UTC, lwsanty commented on sql/migrations/016_jira_issue_labels_lowercase.up.sql
> +CREATE OR REPLACE FUNCTION lower(text[]) RETURNS text[] LANGUAGE SQL IMMUTABLE AS
Done.

2020-09-15 16:05 UTC, dennwc approved these changes

2020-09-15 16:09 UTC, merged