jira -> users table initial
athenianco/metadata pull request #292
Opened 2020-10-20 13:28 UTC by lwsanty

relates to [[DEV-1039]]
relates to [[DEV-1040]]

Signed-off-by: lwsanty <lwsanty@gmail.com>

2020-10-21 07:48 UTC, vmarkovtsev approved these changes

2020-10-21 07:48 UTC, vmarkovtsev commented on sql/migrations/035_jira_user.up.sql
> +ALTER TABLE jira.issue ALTER COLUMN creator_id SET NOT NULL;
Shall we consider renaming "creator" to "reporter", as it is in the JIRA UI? Or does it come directly from JIRA API?

2020-10-21 07:48 UTC, vmarkovtsev commented on sql/migrations/035_jira_user.up.sql
> +    type text NOT NULL,
What's the user type?

2020-10-21 10:22 UTC, lwsanty commented on sql/migrations/035_jira_user.up.sql
> +ALTER TABLE jira.issue ALTER COLUMN creator_id SET NOT NULL;
ouch I have missed that these are different things https://community.atlassian.com/t5/Jira-questions/creator-vs-reporter/qaq-p/1028179

2020-10-21 10:22 UTC, lwsanty commented on sql/migrations/035_jira_user.up.sql
> +    type text NOT NULL,
either atlassian or app

2020-10-21 10:24 UTC, lwsanty commented on sql/migrations/035_jira_user.up.sql
> +ALTER TABLE jira.issue ALTER COLUMN creator_id SET NOT NULL;
I will set reporter then

2020-10-21 16:45 UTC, vmarkovtsev commented
@lwsanty The priority display names in the issue table should be saved lower case (just double-checking).

2020-10-21 16:46 UTC, vmarkovtsev commented
Update: no need for lower case, I glitched.

2020-10-22 08:55 UTC, vmarkovtsev requested changes

2020-10-22 08:55 UTC, vmarkovtsev commented on sql/migrations/035_jira_user.up.sql
> +CREATE INDEX IF NOT EXISTS issue_resolver ON jira.issue(acc_id, created, resolved, lower(priority_name), lower(assignee_display_name));
Having spent a few hours coding sample SQL, these seem to be needed:
```suggestion
CREATE INDEX IF NOT EXISTS issue_reporter ON jira.issue(acc_id, created, resolved, lower(reporter_display_name), lower(priority_name));
CREATE INDEX IF NOT EXISTS issue_resolver ON jira.issue(acc_id, created, resolved, lower(assignee_display_name), lower(priority_name));
CREATE INDEX IF NOT EXISTS issue_commenters ON jira.issue USING GIN(acc_id, created, resolved, commenters_display_names, lower(priority_name));
CREATE INDEX IF NOT EXISTS issue_reporter_active ON jira.issue(acc_id, updated, created, resolved,  lower(reporter_display_name), lower(priority_name));
CREATE INDEX IF NOT EXISTS issue_resolver_active ON jira.issue(acc_id, updated, created, resolved, lower(assignee_display_name), lower(priority_name));
CREATE INDEX IF NOT EXISTS issue_commenters_updated ON jira.issue USING GIN(acc_id, updated, created, resolved, commenters_display_names, lower(priority_name));
```
IDK much about GIN, we really need Denys to adjust here... If it does not work with GIN then we can add it later.

2020-10-22 08:55 UTC, vmarkovtsev commented on sql/migrations/035_jira_user.up.sql
> +ALTER TABLE jira.issue ADD COLUMN commenters_display_names text[];
These should be written lower case, ok?

2020-10-22 12:50 UTC, lwsanty commented on sql/migrations/035_jira_user.up.sql
> +CREATE INDEX IF NOT EXISTS issue_resolver ON jira.issue(acc_id, created, resolved, lower(priority_name), lower(assignee_display_name));
agreed to skip for now

2020-10-22 13:11 UTC, lwsanty commented on sql/migrations/035_jira_user.up.sql
> +ALTER TABLE jira.issue ADD COLUMN commenters_display_names text[];
Done.

2020-10-22 16:22 UTC, vmarkovtsev requested changes

2020-10-22 16:22 UTC, vmarkovtsev commented on sql/migrations/035_jira_user.up.sql
> +CREATE INDEX IF NOT EXISTS issue_resolver ON jira.issue(acc_id, created, resolved, lower(priority_name), lower(assignee_display_name));
The indexes are still the old ones here. I've proposed 6, 4 are normal ones and 2 are GIN-s that we drop.

2020-10-23 09:13 UTC, lwsanty commented on sql/migrations/035_jira_user.up.sql
> +CREATE INDEX IF NOT EXISTS issue_resolver ON jira.issue(acc_id, created, resolved, lower(priority_name), lower(assignee_display_name));
Done.

2020-10-23 09:19 UTC, vmarkovtsev approved these changes

2020-10-23 09:51 UTC, merged